# permissions for end users to view mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongo-operator
    app.kubernetes.io/part-of: mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodb-viewer-role
rules:
- apiGroups:
  - databases.core.yrs.io
  resources:
  - mongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.core.yrs.io
  resources:
  - mongodbs/status
  verbs:
  - get
